name:  CHECK COOKIES

on:
  push:
    branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]
  schedule: # execute every day at 23pm utc (20pm rio tinto)
    - cron: "0 23 * * *"

  workflow_dispatch:

jobs:
  INICIAR-CHECAGEM:
    runs-on: windows-latest
    environment: env  # THIS WAS MISSING
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip' # caching pip dependencies

      - name: install requirements, upload vídeo and start bots # run the run.py to get the latest data
        env:
          GMAIL_FROM: ${{secrets.GMAIL_FROM}}
          GMAIL_FROM_PASSWORD: ${{secrets.GMAIL_FROM_PASSWORD}}
          GMAIL_TO: ${{secrets.GMAIL_TO}}
          MY_API_URL: ${{secrets.MY_API_URL}}
        run: |
          pip install -r requirements.txt
          python checkCookies.py
      # - name: setup node js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: turn on bots # run the run.py to get the latest data
      #   run: node main.js
